config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  get '/search' => 'places#search', :as => 'search_places'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place

  after_create :send_comment_email

  RATINGS = {
  'one star': '1_star',
  'two stars': '2_stars',
  'three stars': '3_stars',
  'four stars': '4_stars',
  'five stars': '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, PictureUploader

  belongs_to :user
	belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  WillPaginate.per_page = 5

  geocoded_by :address
  after_validation :geocode
  validates :name, presence: true, length: { maximum: 55, minimum: 2 }
  validates :address, presence: true
  validates :description, presence: true, length: { maximum: 500 }

  belongs_to :user
  has_many :photos
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :places
  has_many :photos
  has_many :comments

  validates :email, presence: true
  validates :username, presence: true, length: { maximum: 55 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!

	def create
		@place = Place.find(params[:place_id])
		@place.photos.create(photo_params.merge(user: current_user))
		redirect_to place_path(@place)
	end

	private

	def photo_params
		params.require(:photo).permit(:picture, :caption)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def index
    @places = Place.order(:id).paginate(page: params[:page], per_page: 9)
  end

  def new
    @place = Place.new
    @photo = Photo.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to place_path(@place)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: "Not allowed", status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to place_path(@place)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    @place.destroy
    redirect_to root_path
  end

  def search
    @places = Place.all
    @search = params["search"]
    if @search.present?
      @name = @search["name"]
      @places = Place.where("name ILIKE ?", "%#{@name}%").order(:id).paginate(page: params[:page], per_page: 5)
    end
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/_flash_messages.html.erb
<div class="container flash-notice">
  <% if flash[:error].present?  %>
    <div class="col-12 alert alert-danger">
      <%= flash[:error].html_safe %>
    </div>
  <% end %>
  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark sticky-top">
  <div class="container header-container">
    <%= link_to 'FoodStir', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <%= link_to new_place_path, class: "nav-link" do %>
            <i class="fa fa-plus-circle"></i>
            Add a New Place
          <% end %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <%= simple_form_for :search, url: search_places_path, method: "GET", validate: true, html: { class: "form-inline my-2 my-lg-0"} do |f| %>
        <%= f.input :name, label: "", placeholder: "Find a place...", input_html: { value: "" }, class: "form-control mr-sm-2" %> |
        <%= f.submit "SEARCH!", class: "search-btn" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/places/_map.html.erb
<% if @place.latitude.present? && @place.longitude.present? %>
  <script>
    function initMap() {
      let myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %> };

      let map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      let marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
  </script>

  <div id="map"></div>
<% end %>

app/views/places/_maps.html.erb
<% if @place.latitude.present? && @place.longitude.present? %>
  <script>
    function initMap() {
      let myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %> };

      let map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      let marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
  </script>

  <div id="map"></div>
<% end %>

app/views/places/edit.html.erb
<div class=" container booyah-box">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br>
    <%= f.submit 'Update', class: "btn btn-outline-info" %>
  <% end %>
</div>

app/views/places/index.html.erb
<div class="container index-container">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <%= image_tag "place_images/image6.jpg", class: "d-block img-fluid" %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Find the best food places...</h3>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag "place_images/image2.jpg", class: "d-block img-fluid" %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Be a foodster, post a place...</h3>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag "place_images/image4.jpg", class: "d-block img-fluid" %>
        <div class="carousel-caption d-none d-md-block">
          <h3>See what your friends are saying...</h3>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <% if !@places.present? %>
    <h2>Welcome to Foodster, please feel free to add a place...</h2>
    <%= link_to new_place_path, class: "nav-link" do %>
      <i class="fa fa-plus-circle"></i>
      Add a New Place
    <% end %>
  <% else %>
    <div class="row justify-content-center">
      <% @places.each do |place| %>
        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12">
          <div class="card card-index-page">
            <div class="card-img-top card-img-show">
              <% if place.photos.present? %>
                <div>
                  <%= link_to image_tag(place.photos.first.picture.to_s, class: 'index-image-size'), place_path(place) %>
                </div>
              <% end %>
            </div>
            <% if place.comments.present? %>
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <div class="card-body">
                    <h2 class="card-title text-center"><%= link_to place.name, place_path(place), class: "index-card-title" %></h2><hr>
                    <i><%= place.address %></i><br><br>
                    <p class="card-text"><%= place.description %> </p>
                    <% if place.user.present? %>
                      <small>Posted by: <%= place.user.username %></small>
                    <% end %>
                    <button onclick="flip()">flip the card</button>
                  </div>
                </div>
                <div class="flip-card-back">
                  <div class="card-body">
                    <div class="card-text">
                      <blockquote>
                        <% if place.comments.last.humanized_rating.present? %>
                          <b><%= place.comments.last.humanized_rating %></b> -
                        <% end %>
                        <%= place.comments.last.message %><br>
                        <small>Posted by: <%= place.comments.last.user.username %></small>
                      </blockquote>
                    </div>
                  </div>
                </div>
              </div>
            <% else %>
              <div class="card-body">
                <h2 class="card-title text-center"><%= link_to place.name, place_path(place), class: "index-card-title" %></h2><hr>
                <i><%= place.address %></i><br><br>
                <p class="card-text"><%= place.description %> </p>
                <% if place.user.present? %>
                  <small>Posted by: <%= place.user.username %></small>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="d-flex justify-content-center">
      <%= will_paginate @places, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
  <% end %>
</div>

app/views/places/new.html.erb
<div class=" container booyah-box">
  <div class="row">
    <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-xs-12">
      <h1>Enter Your Place Details</h1>
      <%= simple_form_for @place do |f| %>
        <%= f.input :name, label: "Place Name" %>
        <%= f.input :address %>
        <%= f.input :description, class: "new-place-description" %>
        <br>
        <%= f.submit 'Create', class: "btn btn-outline-info" %>
      <% end %>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <%= image_tag 'auth-image', class: "auth-image" %>
    </div>
  </div>
</div>

app/views/places/search.html.erb
<div class="container index-container">
  <% if !@places.present? %>
    <h2>It seems as though that place can't be found, please feel free to create it below...</h2>
    <%= link_to new_place_path, class: "nav-link" do %>
      <i class="fa fa-plus-circle"></i>
      Add a New Place
    <% end %>
  <% else %>
    <h2>Hopefully you found what you're looking for...</h2>
    <div class="row justify-content-center">
      <% @places.each do |place| %>
        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12">
          <div class="card card-index-page">
            <div class="card-img-top card-img-show">
              <% if place.photos.present? %>
                <div>
                  <%= link_to image_tag(place.photos.first.picture.to_s, class: 'index-image-size'), place_path(place) %>
                </div>
              <% end %>
            </div>
            <div class="card-body">
              <h2 class="card-title text-center"><%= link_to place.name, place_path(place), class: "index-card-title" %></h2><hr>
              <i><%= place.address %></i><br><br>
              <p class="card-text"><%= place.description %> </p>
              <% if place.user.present? %>
                <small>Posted by: <%= place.user.username %></small>
              <% end %>
              <% if place.comments.present? %>
                <div class="card-text">
                  <blockquote>
                    <% if place.comments.last.humanized_rating.present? %>
                      <b><%= place.comments.last.humanized_rating %></b> -
                    <% end %>
                    <%= place.comments.last.message %><br>
                    <small>Posted by: <%= place.comments.last.user.username %></small>
                  </blockquote>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="d-flex justify-content-center">
      <%= will_paginate @places, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="container show-container">
  <div class="card show-card-page">
    <% @place.photos.each do |photo| %>
      <div class="card-img-top">
        <%= image_tag photo.picture.to_s, class: 'show-image-size' %>
      </div>
      <% if photo.caption.present? %>
        <p class="text-center"><%= photo.caption %></p>
      <% end %>
    <% end %>
    <div class="card-body">
      <div class="row show-title-div">
        <h1 class="card-title col-xl-10 col-lg-9 col-md-8 col-sm-12 col-xs-12"><%= @place.name %></h1>
        <div class="col-xl-2 col-lg-3 col-md-4 col-sm-12 col-xs-12">
          <button type="button" class="btn btn-block btn-dark buttons add-photo-button" data-toggle="modal" data-target="#photo-modal">Add a photo <i class="fa fa-camera-retro"></i></button>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-lg-5 col-lg-5 col-md-5 show-row-details">
          <small>Posted by: <%= @place.user.username %></small>
          <i class="fa fa-map-marker"></i>
          <i class="card-text"><b>Location: </b><%= @place.address %></i>
          <br/><br/>
          <p class="card-text"><b> Description: </b><%= @place.description %></p>
          <%= render 'places/map' %>
        </div>
        <div class="col-xl-7 col-lg-7 col-md-7">
          <div class="comment-show-div">
            <h4>What the Foodster think...</h4><hr>
            <div class="comment-message-div">
              <% @place.comments.each do |comment| %>
                <blockquote>
                  <span>Foodster <b><%= comment.user.username %></b> says:</span>
                  <br>
                  <%= comment.message %><br>
                  <% if comment.humanized_rating.present? %>
                    <b><%= comment.rating %></b>
                  <% end %>
                </blockquote>
              <% end %>
            </div>
            <h4>Share your thoughts on <%= @place.name %></h4><hr>
            <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
              <%= f.input :message %>
              <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
              <%= f.submit "Add a Comment", class: 'btn btn-outline-dark' %>
            <% end %>
          </div>
        </div>
      </div>
      <hr>
      <div  class="float-right show-edit-destroy-btns">
        <% if current_user && current_user == @place.user %>
          <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-dark buttons' %>
          <%= link_to 'Destroy', place_path(@place),
          method: :delete,
          data: {confirm: 'Are you sure you want to delete this?'},
          class: 'btn btn-danger buttons' %>
        <% end %>
      </div>
    </div>

    <!-- Photo Modal -->
    <div class="modal fade" id="photo-modal" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Add an image</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
            <div class="modal-body">
              <%= f.input :caption, label: "Add an image caption..." %>
              <%= f.input :picture, label: "Choose an image...", class: "picture-upload-button" %>
            </div>
            <div class="modal-footer">
              <%= f.submit "Submit", class: 'btn btn-lg btn-block btn-info modal-submit' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>